apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
spec:
  replicas: {{ .Values.spec.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.spec.template.metadata.labels.app }}
    spec:
      containers:
      - name: {{ .Values.spec.template.spec.containers.name }}
        image: {{ .Values.spec.template.spec.containers.image }}
        ports: {{ .Values.spec.template.spec.containers.ports }}
        - containerPort: {{ .Values.spec.template.spec.containers.port.containerPort }}