apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpscanner-deployment
  labels:
    app: tpscanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tpscanner
  template:
    metadata:
      labels:
        app: tpscanner
    spec:
      containers:
      - name: tpscanner
        image: vale111/m16-17:v2
        ports:
        - containerPort: 5002
