on:
  push:
    branches-ignore:
    - master

name: CI
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: build and push to docker
        uses: actions/checkout@master
      -
        name: Build and (not) push
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ${{ github.sha }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          